/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.awt.event.KeyEvent;

/**
 *
 * @author Ken
 */
public class Login_Authentication extends javax.swing.JFrame {
    boolean auth = false;

    /**
     * Creates new form Login_Authentication
     */
    public Login_Authentication() {
        
        initComponents();
        setVisible(true);
        error.setVisible(false);
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        user_name = new javax.swing.JTextField();
        error = new javax.swing.JLabel();
        proceed = new javax.swing.JButton();
        pass_icon = new javax.swing.JLabel();
        username_icon = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.white);
        setMinimumSize(new java.awt.Dimension(550, 320));
        setResizable(false);
        getContentPane().setLayout(null);

        user_name.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        user_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                user_nameMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user_nameMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                user_nameMouseReleased(evt);
            }
        });
        user_name.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                user_nameMouseMoved(evt);
            }
        });
        user_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_nameActionPerformed(evt);
            }
        });
        user_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                user_nameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                user_nameKeyTyped(evt);
            }
        });
        getContentPane().add(user_name);
        user_name.setBounds(70, 110, 140, 40);

        error.setForeground(new java.awt.Color(204, 0, 51));
        error.setText("The username or password you entered is incorrect");
        getContentPane().add(error);
        error.setBounds(40, 210, 250, 10);

        proceed.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        proceed.setForeground(new java.awt.Color(51, 51, 51));
        proceed.setText("LOGIN");
        proceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedActionPerformed(evt);
            }
        });
        getContentPane().add(proceed);
        proceed.setBounds(40, 230, 90, 40);

        pass_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/un.png"))); // NOI18N
        getContentPane().add(pass_icon);
        pass_icon.setBounds(30, 160, 40, 40);

        username_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/un.png"))); // NOI18N
        getContentPane().add(username_icon);
        username_icon.setBounds(30, 110, 38, 38);

        password.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        password.setEchoChar('|');
        password.setInheritsPopupMenu(true);
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordKeyPressed(evt);
            }
        });
        getContentPane().add(password);
        password.setBounds(70, 160, 140, 40);

        background.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/b2.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 550, 320);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-563)/2, (screenSize.height-360)/2, 563, 360);
    }// </editor-fold>//GEN-END:initComponents

    private void user_nameMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user_nameMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_user_nameMouseMoved

    private void user_nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user_nameMouseClicked
        // TODO add your handling code here:

        
    }//GEN-LAST:event_user_nameMouseClicked

    private void user_nameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user_nameMouseExited
        // TODO add your handling code here:

        
    }//GEN-LAST:event_user_nameMouseExited

    private void user_nameMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user_nameMouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_user_nameMouseReleased

    private void proceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedActionPerformed
        // TODO add your handling code here:
        
        if("admin".equals(password.getText()) && "admin".equals(password.getText())){
            auth = true;
            error.setVisible(false);
            
            this.dispose();
            new Main();
        }
        else error.setVisible(true);

        
    }//GEN-LAST:event_proceedActionPerformed

    private void user_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_nameActionPerformed

    private void user_nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_user_nameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_user_nameKeyTyped

    private void user_nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_user_nameKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        if("admin".equals(password.getText()) && "admin".equals(password.getText())){
            auth = true;
            error.setVisible(false);
            
            this.dispose();
            new Main();
        }
        else error.setVisible(true);
        }
    }//GEN-LAST:event_user_nameKeyPressed

    private void passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        if("admin".equals(password.getText()) && "admin".equals(password.getText())){
            auth = true;
            error.setVisible(false);
            
            this.dispose();
            new Main();
        }
        else error.setVisible(true);
        }
    }//GEN-LAST:event_passwordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Authentication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Authentication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Authentication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Authentication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
    
                new Login_Authentication();
                
    }
    
    
    public boolean pass(boolean auth1){
    return auth1;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel error;
    private javax.swing.JLabel pass_icon;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton proceed;
    private javax.swing.JTextField user_name;
    private javax.swing.JLabel username_icon;
    // End of variables declaration//GEN-END:variables
}
