/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import javax.swing.JOptionPane;

/**
 *
 * @author Ken
 */
public class Months extends javax.swing.JDialog {

    /**
     * Creates new form Months
     */
    String m = "January";
    String days = "01";
    String years = "2013";
    int d = 1;
    int y = 2013;
    public Months(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        month = new javax.swing.JComboBox();
        day = new javax.swing.JComboBox();
        year = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Birthdate");

        month.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        month.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "Febuary", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthActionPerformed(evt);
            }
        });

        day.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        day.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", " " }));
        day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayActionPerformed(evt);
            }
        });

        year.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        year.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990" }));
        year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Select a Birthdate");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jButton1)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-289)/2, (screenSize.height-163)/2, 289, 163);
    }// </editor-fold>//GEN-END:initComponents

    private void monthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthActionPerformed
        String s = (String) month.getSelectedItem();
        
                switch(s){
                case "January":
                        m = s;
                    break;
                case "Febuary":
                    m = s;
                    break;
                case "March":
                   m = s;
                    break;
                case "April":
                    m = s;
                    break;
                case "May":
                    m = s;
                    break;
                case "June":
                    m = s;
                    break;
                case "July":
                   m = s;
                    break;
                case "August":
                   m = s;
                    break;
                case "September":
                    m = s;
                    break;
                case "October":
                    m = s;
                    break;
                case "November":
                    m = s;
                    break;
                case "December":
                    m = s;
                    break;
            
            }
                
    }//GEN-LAST:event_monthActionPerformed

    private void dayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayActionPerformed
        
        String s = (String) day.getSelectedItem();
        
                switch(s){
                case "1":
                    d = 1;
                    break;
                case "2":
                    d = 2;  
                    break;
                case "3":
                  d = 3;
                    break;
                case "4":
                   d = 4;
                    break;
                case "5":
                    d = 5;
                    break;
                case "6":
                    d = 6;
                    break;
                case "7":
                  d = Integer.parseInt(s);
                    break;
                case "8":
                   d = Integer.parseInt(s);
                    break;
                case "9":
                   d = Integer.parseInt(s);
                    break;
                case "10":
                    d = Integer.parseInt(s);
                    break;
                case "11":
                   d = Integer.parseInt(s);
                    break;
                case "12":
                    d = Integer.parseInt(s);
                    break;
                case "13":
                    d = Integer.parseInt(s);
                    break;
                case "14":
                    d = Integer.parseInt(s);  
                    break;
                case "15":
                  d = Integer.parseInt(s);
                    break;
                case "16":
                   d = Integer.parseInt(s);
                    break;
                case "17":
                    d = Integer.parseInt(s);
                    break;
                case "18":
                    d = Integer.parseInt(s);
                    break;
                case "19":
                  d = Integer.parseInt(s);
                    break;
                case "20":
                   d = Integer.parseInt(s);
                    break;
                case "21":
                   d = Integer.parseInt(s);
                    break;
                case "22":
                    d = Integer.parseInt(s);
                    break;
                case "23":
                   d = Integer.parseInt(s);
                    break;
                case "24":
                    d = Integer.parseInt(s);
                    break;
                case "25":
                   d = Integer.parseInt(s);
                    break;
                case "26":
                   d = Integer.parseInt(s);
                    break;
                case "27":
                    d = Integer.parseInt(s);
                    break;
                case "28":
                   d = Integer.parseInt(s);
                    break;
                case "29":
                    d = Integer.parseInt(s);
                    break;
                case "30":
                    d = Integer.parseInt(s);
                    break;
                case "31":
                   d = Integer.parseInt(s);
                    break;
            
            }
                days = Integer.toString(d);
                JOptionPane.showMessageDialog(null, days);
                
                
               
    }//GEN-LAST:event_dayActionPerformed

    private void yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearActionPerformed
        String s = (String) year.getSelectedItem();
        
                switch(s){
                case "2013":
                    y = 2013;
                    break;
                case "2012":
                    y = 2012;  
                    break;
                case "2011":
                  y = 2011;
                    break;
                case "2010":
                   y = 2010;
                    break;
                case "2009":
                    y = 2009;
                    break;
                case "2008":
                    y = 2008;
                    break;
                case "2007":
                  y = 2007;
                    break;
                case "2006":
                   y = 2006;
                    break;
                case "2005":
                   y = 2005;
                    break;
                case "2004":
                    y = 2004;
                    break;
                case "2003":
                   y = 2003;
                    break;
                case "2002":
                    y = 2002;
                    break;
                case "2001":
                    y = 2001;
                    break;
                case "1999":
                    y = 1999;  
                    break;
                case "1998":
                  y = 1998;
                    break;
                case "1997":
                   y = 1997;
                    break;
                case "1996":
                    y = 1996;
                    break;
                case "1995":
                    y = 1995;
                    break;
                case "1994":
                  y = 1994;
                    break;
                case "1993":
                   y = 1993;
                    break;
                case "1992":
                   y = 1992;
                    break;
                case "1991":
                    y = 1991;
                    break;
                case "1990":
                   y = 1990;
                    break;
            
            }
                years = Integer.toString(y);
                JOptionPane.showMessageDialog(null, years);
                
    }//GEN-LAST:event_yearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Months.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Months.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Months.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Months.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                Months dialog = new Months(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox day;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox month;
    private javax.swing.JComboBox year;
    // End of variables declaration//GEN-END:variables
}
